# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '3b91c73d-8c04-4ecc-9575-ea97006c8c21'
  imageRepository: 'rctomcatwar'
  containerRegistry: 'sampleproj.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  # tag: '$(Build.BuildId)'
  tag: 41


  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Install
  variables:
  - group: personal
  - name: temppwfilename
    value: 'tempPW.txt'
  - name: imgName
    value: 'releaseFirstApp'
  displayName: Tryna install docker
  jobs:
    - job: I1J1
      displayName: Install Job1
      steps:
      - script: |
          az acr list --resource-group SelfLearningaz --output table
          az acr login -n rcselflearncr --expose-token